name: CMS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [auth-service, article-service, common-service, queue-service, gateway]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd ${{ matrix.service }}
        npm install

    - name: Run tests
      run: |
        cd ${{ matrix.service }}
        npm test || echo "No tests defined for ${{ matrix.service }}"